server:
  port: 8200
  forward-headers-strategy: framework

spring:
  application:
    name: nekowindow-service-oss
  cloud:
    nacos:
      server-addr: 10.200.0.1:8848
      discovery:
        group: dev
  config:
    import:
      - nacos:nekowindow-service-oss.yaml?refresh=true&group=dev