FROM eclipse-temurin:18-jre

ARG SERVICE_NAME

ENV SERVICE_NAME=$SERVICE_NAME

WORKDIR /app

RUN echo "deb http://mirrors.tencent.com/ubuntu/ jammy main restricted universe multiverse" > /etc/apt/sources.list \
    && echo "deb http://mirrors.tencent.com/ubuntu/ jammy-security main restricted universe multiverse" > /etc/apt/sources.list \
    && echo "deb http://mirrors.tencent.com/ubuntu/ jammy-updates main restricted universe multiverse" > /etc/apt/sources.list \
    && echo "#deb http://mirrors.tencent.com/ubuntu/ jammy-proposed main restricted universe multiverse" > /etc/apt/sources.list \
    && echo "#deb http://mirrors.tencent.com/ubuntu/ jammy-backports main restricted universe multiverse" > /etc/apt/sources.list \
    && echo "deb-src http://mirrors.tencent.com/ubuntu/ jammy main restricted universe multiverse" > /etc/apt/sources.list \
    && echo "deb-src http://mirrors.tencent.com/ubuntu/ jammy-security main restricted universe multiverse" > /etc/apt/sources.list \
    && echo "deb-src http://mirrors.tencent.com/ubuntu/ jammy-updates main restricted universe multiverse" > /etc/apt/sources.list \
    && echo "#deb-src http://mirrors.tencent.com/ubuntu/ jammy-proposed main restricted universe multiverse" > /etc/apt/sources.list \
    && echo "#deb-src http://mirrors.tencent.com/ubuntu/ jammy-backports main restricted universe multiverse" > /etc/apt/sources.list \
    && rm /etc/apt/sources.list.d/debian.sources \
    && apt-get update \
    && apt-get install -y ffmpeg

COPY $SERVICE_NAME/target/$SERVICE_NAME-0.0.1-SNAPSHOT.jar /app/

CMD java -jar $SERVICE_NAME-0.0.1-SNAPSHOT.jar