server:
  port: 8420
  forward-headers-strategy: framework
spring:
  application:
    name: nekowindow-service-encode
  cloud:
    nacos:
      server-addr: 10.200.0.20:8848
  config:
    import: nacos:nekowindow-service-encode.yaml?refresh=true