server:
  port: 8010
  forward-headers-strategy: framework
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.200.0.1:3306/nekowindow_account
    username: nekowindow_dev
    password: password
  application:
    name: nekowindow-service-auth
  cloud:
    nacos:
      discovery:
        server-addr: 10.200.0.1:8848
        group: dev
  data:
    redis:
      host: localhost
      port: 6379

springdoc:
  swagger-ui:
    path: "/swagger/auth/swagger-ui.html"
  api-docs:
    path: "/swagger/auth/api-docs"