server:
  port: 8010
  forward-headers-strategy: framework

spring:
  application:
    name: nekowindow-service-auth
  cloud:
    nacos:
      server-addr: 10.200.0.20:8848
  config:
    import: nacos:nekowindow-service-auth.yaml?refresh=true