server:
  port: 8320
  forward-headers-strategy: framework

spring:
  application:
    name: nekowindow-service-video
  cloud:
    nacos:
      server-addr: 10.200.0.1:8848
  config:
    import: nacos:nekowindow-service-video.yaml?refresh=true