server:
  port: 80
  forward-headers-strategy: framework

spring:
  application:
    name: "nekowindow-gateway"
  cloud:
    nacos:
      discovery:
        server-addr: 10.200.0.1:8848
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost"
              - "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
              - PUT
              - HEAD
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true
      routes:
        - id: auth-service
          uri: lb://nekowindow-service-auth
          predicates:
            - Path=/api/v1/auth/**, /swagger/auth/**
        - id: user-service
          uri: lb://nekowindow-service-user
          predicates:
            - Path=/api/v1/user/**, /swagger/user/**
        - id: video-service
          uri: lb://nekowindow-service-video
          predicates:
            - Path=/api/v1/video/**, /swagger/video/**
        - id: oss-service
          uri: lb://nekowindow-service-oss
          predicates:
            - Path=/api/v1/oss/**, /swagger/oss/**
        - id: encode-service
          uri: lb://nekowindow-service-encode
          predicates:
            - Path=/api/v1/encode/**, /swagger/encode/**
#        - id: openapi-proxy
#          uri: http://localhost
#          predicates:
#            - Path=/*/v3/api-docs/**

springdoc:
  swagger-ui:
    urls:
      - name: user
        url: /swagger/user/api-docs
      - name: auth
        url: /swagger/auth/api-docs
      - name: video
        url: /swagger/video/api-docs
      - name: oss
        url: /swagger/oss/api-docs
      - name: encode
        url: /swagger/encode/api-docs
    enabled: true
  cache:
    disabled: true
