spring:
  application:
    name: nekowindow-gateway
  cloud:
    nacos:
      server-addr: 10.200.0.1:8848
      discovery:
        group: dev
  config:
    import:
      - nacos:nekowindow-gateway.yaml?refresh=true&group=dev
server:
  port: 80
