server:
  port: 8020
  forward-headers-strategy: framework

spring:
  application:
    name: nekowindow-service-user
  cloud:
    nacos:
      server-addr: 10.200.0.1:8848
      discovery:
        group: dev
  config:
    import:
      - nacos:nekowindow-service-user.yaml?refresh=true&group=dev